#!/usr/bin/perl

open (IN,"dir") ||(die "can not open the file input.txt\n$!");
my @all = <IN>;
foreach $line(@all)
{
    if (line !~ /^$/) {
        $line =~ s/\s{4}//;
        print $line;
    }

}
